import { NextRequest } from "next/server"

// Verify scanner token. Fails closed in production if no token is configured,
// rather than silently accepting the well-known development default.
// Shared by every scanner-facing endpoint (check-in, heartbeat).
export function verifyScannerToken(request: NextRequest): boolean {
  const token = request.headers.get("x-scanner-token")
  const validToken = process.env.SCANNER_DEVICE_TOKEN
  if (!validToken) {
    if (process.env.NODE_ENV === "production") return false
    return token === "dev-scanner-token"
  }
  return token === validToken
}

// Device ids are generated by the mobile app (32 hex chars) but stay
// permissive enough for other scanner clients.
export const DEVICE_ID_PATTERN = /^[A-Za-z0-9_-]{8,64}$/
